services:
  postgres:
    image: postgres:16-alpine
    hostname: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: mocktail
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin@123
    volumes:
      - postgresdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 2s
      retries: 12

  backend:
    build:
      context: services/Backend
      dockerfile: Docker/Dockerfile
    container_name: backend
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__BackendDb=${ConnectionStrings__BackendDb}

  content:
    build:
      context: services/Content
      dockerfile: Docker/Dockerfile
    container_name: content

  generator:
    build:
      context: services/Generator
      dockerfile: Docker/Dockerfile
    container_name: generator
    env_file:
      - .env

  auth:
    build:
      context: services/Auth
      dockerfile: Docker/Dockerfile
    container_name: auth
    environment:
      ConnectionStrings__AuthDb: ${ConnectionStrings__AuthDb}
    depends_on:
      postgres:
        condition: service_healthy

  gateway:
    build:
      context: services/Gateway
      dockerfile: Dockerfile
    container_name: gateway
    depends_on:
      - backend
      - content
      - generator
      - auth

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - gateway

volumes:
  postgresdata:
    external: true
