version: "3.8"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: mssql
    container_name: mssql
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Admin@123
      MSSQL_SA_PASSWORD: Admin@123

  backend:
    build:
      context: services/Backend
      dockerfile: Dockerfile
    container_name: backend
    command: dotnet watch run

  content:
    build:
      context: services/Content
      dockerfile: Dockerfile
    container_name: content
    command: dotnet watch run

  generator:
    build:
      context: services/Generator
      dockerfile: Dockerfile
    container_name: generator
    command: dotnet watch run

  auth:
    build:
      context: services/Auth
      dockerfile: Dockerfile
    container_name: auth
    command: dotnet watch run

  gateway:
    build:
      context: services/Gateway
      dockerfile: Dockerfile
    container_name: gateway
    depends_on:
      - backend
      - content
      - generator
      - auth
    command: dotnet watch run

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - gateway
    command: npm run dev
