services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: mssql
    container_name: mssql
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Admin@123
      MSSQL_SA_PASSWORD: Admin@123
    volumes:
      - mssqldata:/var/opt/mssql

  backend:
    build:
      context: services
      dockerfile: Backend/Docker/Dockerfile
    container_name: backend

  content:
    build:
      context: services
      dockerfile: Content/Docker/Dockerfile
    container_name: content

  generator:
    build:
      context: services/Generator
      dockerfile: Docker/Dockerfile
    container_name: generator
    env_file:
      - .env

  auth:
    build:
      context: services/Auth
      dockerfile: Docker/Dockerfile
    container_name: auth
    depends_on:
      - mssql

  gateway:
    build:
      context: services/Gateway
      dockerfile: Dockerfile
    container_name: gateway
    depends_on:
      - backend
      - content
      - generator
      - auth

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - gateway

volumes:
  mssqldata:
    external: true
