services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: mssql
    container_name: mssql
    platform: linux/amd64
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Admin@123
      MSSQL_SA_PASSWORD: Admin@123
    volumes:
      - mssqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/1433'"]
      interval: 5s
      timeout: 2s
      retries: 12

  backend:
    build:
      context: services
      dockerfile: Backend/Docker/Dockerfile
    container_name: backend
    depends_on:
      - mssql
    environment:
      - ConnectionStrings__BackendDb=${ConnectionStrings__BackendDb}

  content:
    build:
      context: services
      dockerfile: Content/Docker/Dockerfile
    container_name: content

  generator:
    build:
      context: services/Generator
      dockerfile: Docker/Dockerfile
    container_name: generator
    env_file:
      - .env

  auth:
    build:
      context: services/Auth
      dockerfile: Docker/Dockerfile
    container_name: auth
    environment:
      ConnectionStrings__AuthDb: ${ConnectionStrings__AuthDb}
    depends_on:
      mssql:
        condition: service_healthy

  gateway:
    build:
      context: services/Gateway
      dockerfile: Dockerfile
    container_name: gateway
    depends_on:
      - backend
      - content
      - generator
      - auth

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - gateway

volumes:
  mssqldata:
    external: true
