services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"

  content:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"

  generator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:80"

  auth:
    build:
      dockerfile: Docker/Dockerfile.dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5005:80"
    volumes:
      - ./services/Auth:/src

  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:8080"

  frontend:
    environment:
      - NODE_ENV=development
    ports:
      - "80:80"
