services:
  backend:
    build:
      dockerfile: Docker/Dockerfile.dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"
    volumes:
      - ./services/Backend:/src
      - ./services/Shared:/Shared

  content:
    build:
      dockerfile: Docker/Dockerfile.dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"
    volumes:
      - ./services/Content:/src
      - ./services/Shared:/Shared

  generator:
    build:
      dockerfile: Docker/Dockerfile.dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:80"
    volumes:
      - ./services/Generator:/src

  auth:
    build:
      dockerfile: Docker/Dockerfile.dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5005:80"
    volumes:
      - ./services/Auth:/src

  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5006:8080"

  frontend:
    environment:
      - NODE_ENV=development
    ports:
      - "80:80"
