FROM mcr.microsoft.com/dotnet/sdk:9.0 AS runtime
WORKDIR /src

RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

COPY Auth.csproj .
RUN dotnet restore

COPY . .

CMD ["dotnet", "run", "--project" , "Auth.csproj",  "--urls", "https://*:443;http://*:80"]
