FROM mcr.microsoft.com/dotnet/sdk:9.0 AS runtime
WORKDIR /src

COPY Generator.csproj .
RUN dotnet restore

COPY . .

CMD ["dotnet", "watch", "run", "--project" , "Generator.csproj",  "--urls", "https://*:443;http://*:80"]
