FROM mcr.microsoft.com/dotnet/sdk:9.0 AS runtime
WORKDIR /src

# Simple: just install the native protobuf compiler
RUN apt-get update && apt-get install -y protobuf-compiler && rm -rf /var/lib/apt/lists/*

COPY Content.csproj .
RUN dotnet restore

COPY . .

CMD ["dotnet", "run", "--project" , "Content.csproj", "--urls", "https://*:443;http://*:80"]
