FROM mcr.microsoft.com/dotnet/sdk:9.0 AS runtime
WORKDIR /src

# Copy the Shared directory first
COPY Shared ./Shared/

COPY Content/Content.csproj .
RUN dotnet restore

COPY Content/ .

CMD ["dotnet", "watch", "run", "--project" , "Content.csproj",  "--urls", "https://*:443;http://*:80"]
