// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyService.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250608221634_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyService.Models.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("KeyWords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RelatedProjectId")
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("Schema")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<Guid>>("UsedIn")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.HasKey("Id");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("MyService.Models.Template", b =>
                {
                    b.OwnsMany("MyService.Models.Release", "Releases", b1 =>
                        {
                            b1.Property<Guid>("TemplateId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Author")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Comment")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Version")
                                .HasColumnType("integer");

                            b1.HasKey("TemplateId", "Author", "CreatedAt");

                            b1.ToTable("Release");

                            b1.WithOwner()
                                .HasForeignKey("TemplateId");

                            b1.OwnsOne("MyService.Models.Change", "Changes", b2 =>
                                {
                                    b2.Property<Guid>("ReleaseTemplateId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("ReleaseAuthor")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("ReleaseCreatedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<string>("Description")
                                        .HasColumnType("text");

                                    b2.PrimitiveCollection<List<string>>("KeyWords")
                                        .IsRequired()
                                        .HasColumnType("text[]");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<JsonDocument>("Schema")
                                        .IsRequired()
                                        .HasColumnType("jsonb");

                                    b2.HasKey("ReleaseTemplateId", "ReleaseAuthor", "ReleaseCreatedAt");

                                    b2.ToTable("Release");

                                    b2.WithOwner()
                                        .HasForeignKey("ReleaseTemplateId", "ReleaseAuthor", "ReleaseCreatedAt");
                                });

                            b1.Navigation("Changes")
                                .IsRequired();
                        });

                    b.Navigation("Releases");
                });
#pragma warning restore 612, 618
        }
    }
}
