// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyService.Data;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250702235552_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyService.Models.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("KeyWords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RelatedProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("UsedIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("MyService.Models.Template", b =>
                {
                    b.OwnsMany("MyService.Models.Release", "Releases", b1 =>
                        {
                            b1.Property<Guid>("TemplateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Author")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Comment")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Version")
                                .HasColumnType("int");

                            b1.HasKey("TemplateId", "Author", "CreatedAt");

                            b1.ToTable("Release");

                            b1.WithOwner()
                                .HasForeignKey("TemplateId");

                            b1.OwnsOne("MyService.Models.Change", "Changes", b2 =>
                                {
                                    b2.Property<Guid>("ReleaseTemplateId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("ReleaseAuthor")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<DateTime>("ReleaseCreatedAt")
                                        .HasColumnType("datetime2");

                                    b2.Property<string>("Description")
                                        .HasColumnType("nvarchar(max)");

                                    b2.PrimitiveCollection<string>("KeyWords")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Schema")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ReleaseTemplateId", "ReleaseAuthor", "ReleaseCreatedAt");

                                    b2.ToTable("Release");

                                    b2.WithOwner()
                                        .HasForeignKey("ReleaseTemplateId", "ReleaseAuthor", "ReleaseCreatedAt");
                                });

                            b1.Navigation("Changes")
                                .IsRequired();
                        });

                    b.Navigation("Releases");
                });
#pragma warning restore 612, 618
        }
    }
}
