FROM mcr.microsoft.com/dotnet/sdk:9.0 AS runtime
WORKDIR /src

RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

# Simple: just install the native protobuf compiler
RUN apt-get update && apt-get install -y protobuf-compiler && rm -rf /var/lib/apt/lists/*

COPY Backend.csproj .
RUN dotnet restore

COPY . .

CMD ["dotnet", "run", "--project" , "Backend.csproj",  "--urls", "https://*:443;http://*:80"]
