FROM mcr.microsoft.com/dotnet/sdk:9.0 AS runtime
WORKDIR /src

COPY Backend/Backend.csproj .
RUN dotnet restore

COPY Backend/ .

CMD ["dotnet", "watch", "run", "--project" , "Backend.csproj",  "--urls", "https://*:443;http://*:80"]
